#include "ddb/concurrency/lock_manager.h"
#include <algorithm>
namespace ddb::concurrency {
namespace { bool conflicts(LockMode requested, LockMode held) { return requested == LockMode::Exclusive || held == LockMode::Exclusive; } }
bool LockManager::compatible(const Transaction& tx, ResourceId resource, LockMode mode) const { const auto it=table_.find(resource); if(it==table_.end()) return true; for(const auto& holder:it->second) if(holder.transaction_id!=tx.id() && conflicts(mode,holder.mode)) return false; return true; }
bool LockManager::requester_is_younger_than_conflict(const Transaction& tx,ResourceId resource,LockMode mode) const { const auto it=table_.find(resource); if(it==table_.end()) return false; for(const auto& holder:it->second) if(holder.transaction_id!=tx.id()&&conflicts(mode,holder.mode)&&tx.id()>holder.transaction_id) return true; return false; }
bool LockManager::lock_shared(Transaction& tx,ResourceId resource){return lock(tx,resource,LockMode::Shared);}
bool LockManager::lock_exclusive(Transaction& tx,ResourceId resource){return lock(tx,resource,LockMode::Exclusive);}
bool LockManager::lock(Transaction& tx,ResourceId resource,LockMode mode){std::unique_lock guard(mutex_);if(tx.state()!=TransactionState::Growing)return false;for(;;){auto& holders=table_[resource];auto own=std::find_if(holders.begin(),holders.end(),[&](const Holder& h){return h.transaction_id==tx.id();});if(own!=holders.end()){if(own->mode==mode)return true;if(own->mode==LockMode::Exclusive&&mode==LockMode::Shared)return false;}
if(compatible(tx,resource,mode)){if(own!=holders.end())own->mode=LockMode::Exclusive;else {holders.push_back({tx.id(),mode});held_[tx.id()].insert(resource);}return true;}
if(requester_is_younger_than_conflict(tx,resource,mode)){release_all(tx);tx.state_.store(TransactionState::Aborted);changed_.notify_all();return false;}
changed_.wait(guard,[&]{return tx.state()==TransactionState::Aborted||compatible(tx,resource,mode);});if(tx.state()!=TransactionState::Growing)return false;}}
bool LockManager::unlock(Transaction& tx,ResourceId resource){std::lock_guard guard(mutex_);if(tx.state()!=TransactionState::Growing&&tx.state()!=TransactionState::Shrinking)return false;auto it=table_.find(resource);if(it==table_.end())return false;auto& holders=it->second;auto own=std::find_if(holders.begin(),holders.end(),[&](const Holder& h){return h.transaction_id==tx.id();});if(own==holders.end())return false;holders.erase(own);if(holders.empty())table_.erase(it);auto held=held_.find(tx.id());if(held!=held_.end()){held->second.erase(resource);if(held->second.empty())held_.erase(held);}tx.state_.store(TransactionState::Shrinking);changed_.notify_all();return true;}
void LockManager::release_all(Transaction& tx){auto held=held_.find(tx.id());if(held==held_.end())return;for(const auto& resource:held->second){auto entries=table_.find(resource);if(entries!=table_.end()){auto& v=entries->second;v.erase(std::remove_if(v.begin(),v.end(),[&](const Holder& h){return h.transaction_id==tx.id();}),v.end());if(v.empty())table_.erase(entries);}}held_.erase(held);}
void LockManager::commit(Transaction& tx){std::lock_guard guard(mutex_);if(tx.state()==TransactionState::Committed||tx.state()==TransactionState::Aborted)return;release_all(tx);tx.state_.store(TransactionState::Committed);changed_.notify_all();}
void LockManager::abort(Transaction& tx){std::lock_guard guard(mutex_);if(tx.state()==TransactionState::Committed||tx.state()==TransactionState::Aborted)return;release_all(tx);tx.state_.store(TransactionState::Aborted);changed_.notify_all();}
std::size_t LockManager::lock_count()const{std::lock_guard guard(mutex_);std::size_t n=0;for(const auto& [_,v]:table_)n+=v.size();return n;}std::size_t LockManager::held_lock_count(const Transaction& tx)const{std::lock_guard guard(mutex_);auto it=held_.find(tx.id());return it==held_.end()?0:it->second.size();}bool LockManager::holds(const Transaction& tx,ResourceId r,LockMode m)const{std::lock_guard guard(mutex_);auto it=table_.find(r);if(it==table_.end())return false;return std::any_of(it->second.begin(),it->second.end(),[&](const Holder& h){return h.transaction_id==tx.id()&&h.mode==m;});}
}
