#pragma once
#include <algorithm>
#include <memory>
#include <sstream>
#include <unordered_map>
#include "ddb/execution/table_heap.h"
namespace ddb::execution {
class Executor { public: virtual ~Executor()=default; virtual void init()=0; virtual bool next(Tuple&)=0; };
class Plan { public: virtual ~Plan()=default; [[nodiscard]] virtual std::string explain(std::size_t indent=0)const=0; };
using PlanPtr=std::shared_ptr<const Plan>;
struct Predicate { enum class Op { Eq, Ne, Lt, Le, Gt, Ge }; std::size_t column; Op op; Value value; [[nodiscard]] bool matches(const Tuple&t)const {auto c=compare_values(t.values.at(column),value);switch(op){case Op::Eq:return c==0;case Op::Ne:return c!=0;case Op::Lt:return c<0;case Op::Le:return c<=0;case Op::Gt:return c>0;case Op::Ge:return c>=0;}return false;} };
inline std::string pad(std::size_t n){return std::string(n,' ');} inline const char* opname(Predicate::Op o){static constexpr const char* x[]={"=","!=","<","<=",">",">="};return x[static_cast<int>(o)];}
class SeqScanPlan final:public Plan { public: explicit SeqScanPlan(TableHeap&t,std::string name="table"):table(t),label(std::move(name)){} TableHeap&table;std::string label;std::string explain(std::size_t i=0)const override{return pad(i)+"SeqScan["+label+"]";} };
class IndexScanPlan final:public Plan { public: IndexScanPlan(TableHeap&t,index::BPlusTree&x,index::KeyType key):table(t),tree(x),key(key){}TableHeap&table;index::BPlusTree&tree;index::KeyType key;std::string explain(std::size_t i=0)const override{return pad(i)+"IndexScan[key = "+std::to_string(key)+"]";} };
class FilterPlan final:public Plan { public: FilterPlan(PlanPtr c,Predicate p):child(std::move(c)),predicate(std::move(p)){}PlanPtr child;Predicate predicate;std::string explain(std::size_t i=0)const override{return pad(i)+"Filter[column "+std::to_string(predicate.column)+" "+opname(predicate.op)+"]\n"+child->explain(i+2);} };
class ProjectionPlan final:public Plan { public: ProjectionPlan(PlanPtr c,std::vector<std::size_t>x):child(std::move(c)),columns(std::move(x)){}PlanPtr child;std::vector<std::size_t> columns;std::string explain(std::size_t i=0)const override{std::ostringstream s;s<<pad(i)<<"Projection[";for(auto c:columns)s<<c<<' ';s<<"]\n"<<child->explain(i+2);return s.str();} };
struct SortKey {std::size_t column;bool ascending{true};};
class SortPlan final:public Plan { public: SortPlan(PlanPtr c,std::vector<SortKey>k):child(std::move(c)),keys(std::move(k)){}PlanPtr child;std::vector<SortKey>keys;std::string explain(std::size_t i=0)const override{return pad(i)+"Sort\n"+child->explain(i+2);} };
enum class AggregateKind { Count, Sum, Min, Max, Avg }; struct AggregateSpec {AggregateKind kind;std::optional<std::size_t> column;};
class AggregatePlan final:public Plan { public: AggregatePlan(PlanPtr c,std::vector<AggregateSpec>a,std::vector<std::size_t>g={}):child(std::move(c)),aggregates(std::move(a)),groups(std::move(g)){}PlanPtr child;std::vector<AggregateSpec>aggregates;std::vector<std::size_t>groups;std::string explain(std::size_t i=0)const override{return pad(i)+"Aggregate\n"+child->explain(i+2);} };
class JoinPlan final:public Plan { public: JoinPlan(PlanPtr l,PlanPtr r,std::size_t a,std::size_t b):left(std::move(l)),right(std::move(r)),left_column(a),right_column(b){}PlanPtr left,right;std::size_t left_column,right_column;std::string explain(std::size_t i=0)const override{return pad(i)+"NestedLoopJoin\n"+left->explain(i+2)+"\n"+right->explain(i+2);} };
class SeqScanExecutor final:public Executor {public:explicit SeqScanExecutor(TableHeap&t):table_(t){}void init()override{rows_=table_.scan();pos_=0;}bool next(Tuple&o)override{if(pos_==rows_.size())return false;o=rows_[pos_++].second;return true;}private:TableHeap&table_;std::vector<std::pair<RecordId,Tuple>>rows_;std::size_t pos_{};};
class IndexScanExecutor final:public Executor {public:IndexScanExecutor(TableHeap&t,index::BPlusTree&x,index::KeyType k):table_(t),tree_(x),key_(k){}void init()override{done_=false;}bool next(Tuple&o)override{if(done_)return false;done_=true;RecordId r;if(!tree_.get_value(key_,r))return false;auto t=table_.get(r);if(!t)return false;o=std::move(*t);return true;}private:TableHeap&table_;index::BPlusTree&tree_;index::KeyType key_;bool done_{};};
class FilterExecutor final:public Executor {public:FilterExecutor(std::unique_ptr<Executor>c,Predicate p):child_(std::move(c)),p_(std::move(p)){}void init()override{child_->init();}bool next(Tuple&o)override{while(child_->next(o))if(p_.matches(o))return true;return false;}private:std::unique_ptr<Executor>child_;Predicate p_;};
class ProjectionExecutor final:public Executor {public:ProjectionExecutor(std::unique_ptr<Executor>c,std::vector<std::size_t>x):child_(std::move(c)),cols_(std::move(x)){}void init()override{child_->init();}bool next(Tuple&o)override{Tuple in;if(!child_->next(in))return false;o.values.clear();for(auto c:cols_)o.values.push_back(in.values.at(c));return true;}private:std::unique_ptr<Executor>child_;std::vector<std::size_t>cols_;};
class MaterializedExecutor:public Executor {public:void init()override{pos_=0;}bool next(Tuple&o)override{if(pos_==rows_.size())return false;o=rows_[pos_++];return true;}protected:std::vector<Tuple>rows_;std::size_t pos_{};};
class SortExecutor final:public MaterializedExecutor {public:SortExecutor(std::unique_ptr<Executor>c,std::vector<SortKey>k):child_(std::move(c)),keys_(std::move(k)){}void init()override{rows_.clear();child_->init();Tuple t;while(child_->next(t))rows_.push_back(t);std::stable_sort(rows_.begin(),rows_.end(),[this](const Tuple&a,const Tuple&b){for(auto k:keys_){auto c=compare_values(a.values.at(k.column),b.values.at(k.column));if(c)return k.ascending?c<0:c>0;}return false;});MaterializedExecutor::init();}private:std::unique_ptr<Executor>child_;std::vector<SortKey>keys_;};
class AggregateExecutor final:public MaterializedExecutor {public:AggregateExecutor(std::unique_ptr<Executor>c,std::vector<AggregateSpec>a,std::vector<std::size_t>g):child_(std::move(c)),aggs_(std::move(a)),groups_(std::move(g)){}void init()override{rows_.clear();child_->init();std::vector<Tuple>in;Tuple t;while(child_->next(t))in.push_back(t);std::vector<std::vector<Tuple>> buckets;if(groups_.empty())buckets.push_back(in);else for(auto&x:in){auto it=std::find_if(buckets.begin(),buckets.end(),[&](auto&b){return !b.empty()&&std::all_of(groups_.begin(),groups_.end(),[&](auto c){return b[0].values[c]==x.values[c];});});if(it==buckets.end())buckets.push_back({x});else it->push_back(x);}for(auto&b:buckets){Tuple out;if(!b.empty())for(auto g:groups_)out.values.push_back(b[0].values[g]);for(auto a:aggs_){if(a.kind==AggregateKind::Count){out.values.emplace_back(static_cast<std::int64_t>(b.size()));continue;}if(b.empty())continue;auto col=*a.column;Value v=b[0].values[col];if(a.kind==AggregateKind::Min||a.kind==AggregateKind::Max){for(auto&r:b)if((a.kind==AggregateKind::Min&&compare_values(r.values[col],v)<0)||(a.kind==AggregateKind::Max&&compare_values(r.values[col],v)>0))v=r.values[col];out.values.push_back(v);}else {double sum=0;for(auto&r:b)sum+=std::visit([](auto z)->double{using T=decltype(z);if constexpr(std::is_same_v<T,std::int64_t>||std::is_same_v<T,double>)return z;else throw std::invalid_argument("SUM/AVG requires numeric column");},r.values[col]);out.values.emplace_back(a.kind==AggregateKind::Avg?sum/b.size():sum);}}rows_.push_back(std::move(out));}MaterializedExecutor::init();}private:std::unique_ptr<Executor>child_;std::vector<AggregateSpec>aggs_;std::vector<std::size_t>groups_;};
class NestedLoopJoinExecutor final:public MaterializedExecutor {public:NestedLoopJoinExecutor(std::unique_ptr<Executor>l,std::unique_ptr<Executor>r,std::size_t a,std::size_t b):left_(std::move(l)),right_(std::move(r)),a_(a),b_(b){}void init()override{rows_.clear();std::vector<Tuple>rs;right_->init();Tuple t;while(right_->next(t))rs.push_back(t);left_->init();while(left_->next(t))for(auto&r:rs)if(t.values.at(a_)==r.values.at(b_)){Tuple x=t;x.values.insert(x.values.end(),r.values.begin(),r.values.end());rows_.push_back(std::move(x));}MaterializedExecutor::init();}private:std::unique_ptr<Executor>left_,right_;std::size_t a_,b_;};
[[nodiscard]] inline std::unique_ptr<Executor> make_executor(const Plan& p){if(auto x=dynamic_cast<const SeqScanPlan*>(&p))return std::make_unique<SeqScanExecutor>(x->table);if(auto x=dynamic_cast<const IndexScanPlan*>(&p))return std::make_unique<IndexScanExecutor>(x->table,x->tree,x->key);if(auto x=dynamic_cast<const FilterPlan*>(&p))return std::make_unique<FilterExecutor>(make_executor(*x->child),x->predicate);if(auto x=dynamic_cast<const ProjectionPlan*>(&p))return std::make_unique<ProjectionExecutor>(make_executor(*x->child),x->columns);if(auto x=dynamic_cast<const SortPlan*>(&p))return std::make_unique<SortExecutor>(make_executor(*x->child),x->keys);if(auto x=dynamic_cast<const AggregatePlan*>(&p))return std::make_unique<AggregateExecutor>(make_executor(*x->child),x->aggregates,x->groups);if(auto x=dynamic_cast<const JoinPlan*>(&p))return std::make_unique<NestedLoopJoinExecutor>(make_executor(*x->left),make_executor(*x->right),x->left_column,x->right_column);throw std::invalid_argument("unknown execution plan");}
}
