#include <filesystem>
#include <iostream>
#include <random>
#include "ddb/execution/executor.h"
namespace {
int failures=0;
#define EXPECT(x) do{if(!(x)){++failures;std::cerr<<__FUNCTION__<<": " #x "\n";}}while(false)
using namespace ddb; using namespace execution;
std::filesystem::path path(){auto p=std::filesystem::temp_directory_path()/"ddb_execution_test.db";std::error_code e;std::filesystem::remove(p,e);return p;}
Schema schema() {return Schema({{"id",ValueType::Int64},{"name",ValueType::String},{"score",ValueType::Double},{"active",ValueType::Boolean}});}
Tuple row(int i){return Tuple{{std::int64_t(i),std::string("user")+std::to_string(i),double(i)*1.5,i%2==0}};}
std::vector<Tuple> collect(Executor&e){std::vector<Tuple>v;Tuple t;e.init();while(e.next(t))v.push_back(t);return v;}
void heap_and_executors(){auto db=path();storage::PageId meta;{storage::PageManager pm(db);buffer::BufferPoolManager bp(pm,3);meta=TableHeap::create(pm,bp,schema());TableHeap h(pm,bp,meta,schema());std::vector<RecordId> ids;for(int i=0;i<300;++i)ids.push_back(*h.insert(row(i)));EXPECT(h.scan().size()==300);EXPECT(h.get(ids[7])==row(7));EXPECT(h.erase(ids[7]));EXPECT(!h.get(ids[7]));EXPECT(h.scan().size()==299);EXPECT(h.validate_invariants());auto seq=std::make_shared<SeqScanPlan>(h,"users");auto filter=std::make_shared<FilterPlan>(seq,Predicate{0,Predicate::Op::Ge,std::int64_t(295)});auto projection=std::make_shared<ProjectionPlan>(filter,std::vector<std::size_t>{1,2});auto out=collect(*make_executor(*projection));EXPECT(out.size()==5&&out[0].values.size()==2);auto sort=SortPlan(seq,{{0,false}});out=collect(*make_executor(sort));EXPECT(std::get<std::int64_t>(out[0].values[0])==299);auto agg=AggregatePlan(seq,{{AggregateKind::Count,std::nullopt},{AggregateKind::Avg,0}},{3});out=collect(*make_executor(agg));EXPECT(out.size()==2&&out[0].values.size()==3);auto join=JoinPlan(seq,seq,0,0);out=collect(*make_executor(join));EXPECT(out.size()==299);EXPECT(bp.validate_invariants());for(std::uint64_t p=0;p<pm.page_count();++p)EXPECT(!bp.pin_count(storage::PageId(p)).value_or(0));h.flush();}{storage::PageManager pm(db);buffer::BufferPoolManager bp(pm,2);TableHeap h(pm,bp,meta,schema());EXPECT(h.scan().size()==299);EXPECT(h.validate_invariants());}std::error_code e;std::filesystem::remove(db,e);}
void index_and_randomized_reference(){auto db=path();storage::PageManager pm(db);buffer::BufferPoolManager bp(pm,4);auto hm=TableHeap::create(pm,bp,schema());TableHeap h(pm,bp,hm,schema());auto im=index::BPlusTree::create(pm,bp,{4,4});index::BPlusTree tree(pm,bp,im);std::mt19937 rng(42);std::vector<int> ref;for(int i=0;i<120;++i){int x=i*100+int(rng()%100);auto rid=*h.insert(row(x));EXPECT(tree.insert(x,rid));ref.push_back(x);}for(int x:ref){IndexScanPlan ip(h,tree,x);auto got=collect(*make_executor(ip));EXPECT(got.size()==1&&std::get<std::int64_t>(got[0].values[0])==x);SeqScanPlan sp(h);FilterPlan fp(std::make_shared<SeqScanPlan>(sp),Predicate{0,Predicate::Op::Eq,std::int64_t(x)});EXPECT(collect(*make_executor(fp))==got);}EXPECT(tree.validate_invariants());EXPECT(h.validate_invariants());EXPECT(bp.validate_invariants());}
}
int main(){try{heap_and_executors();index_and_randomized_reference();}catch(const std::exception&e){++failures;std::cerr<<e.what()<<'\n';}if(failures){std::cerr<<failures<<" failures\n";return 1;}std::cout<<"All execution tests passed\n";}
