#include <cstring>
#include <filesystem>
#include <fstream>
#include <iostream>
#include <stdexcept>

#include "ddb/concurrency/transaction_coordinator.h"
#include "ddb/concurrency/transactional_access.h"
#include "ddb/recovery/redo_engine.h"

namespace { using namespace ddb;
std::filesystem::path path(const char* name){auto file=std::filesystem::temp_directory_path()/name;std::error_code error;std::filesystem::remove(file,error);std::filesystem::remove(file.string()+".wal",error);return file;}
std::vector<char> wal_bytes(const std::filesystem::path& file){std::ifstream input(file,std::ios::binary);return {std::istreambuf_iterator<char>(input),std::istreambuf_iterator<char>()};}
void rewind_to_before_images(const recovery::RecoveryState& state,buffer::BufferPoolManager& pool){for(auto it=state.mutations.rbegin();it!=state.mutations.rend();++it){auto* page=pool.fetch_page(it->mutation.page_id);if(!page)throw std::runtime_error("cannot pin crash-state page");std::memcpy(page->data(),it->mutation.before_image.data(),it->mutation.before_image.size());page->set_lsn(0);if(!pool.unpin_page(it->mutation.page_id,true))throw std::runtime_error("cannot unpin crash-state page");}}
index::RecordId value(std::int64_t key){return {storage::PageId(static_cast<std::uint64_t>(key+100)),static_cast<std::uint32_t>(key)};}

void bplus_redo(){const auto db=path("ddb_redo_tree.db"),wal=std::filesystem::path(db.string()+".wal");storage::PageManager pages(db);storage::LogManager log(wal);buffer::BufferPoolManager pool(pages,64,&log);const auto metadata=index::BPlusTree::create(pages,pool,{3,3});index::BPlusTree tree(pages,pool,metadata);concurrency::TransactionManager manager(&log);concurrency::LockManager locks;concurrency::TransactionCoordinator coordinator(locks,&log);concurrency::TransactionalBPlusTree transactional(tree,locks);auto transaction=manager.begin();for(std::int64_t key=1;key<=80;++key)if(!transactional.insert(transaction,key,value(key)))throw std::runtime_error("tree insert");for(std::int64_t key=2;key<=30;key+=2)if(!transactional.remove(transaction,key))throw std::runtime_error("tree remove");coordinator.commit(transaction);const auto state=recovery::RecoveryAnalyzer::analyze(log);const auto before=wal_bytes(wal);pool.flush_all_pages();rewind_to_before_images(state,pool);pool.flush_all_pages();recovery::ReplayContext replay(pages,pool);const auto metrics=recovery::RedoEngine::run(state,replay);if(!metrics.mutations_applied||wal_bytes(wal)!=before)throw std::runtime_error("tree REDO did not replay immutably");pool.flush_all_pages();index::BPlusTree recovered(pages,pool,metadata);if(!recovered.validate_invariants())throw std::runtime_error("tree REDO invariant");for(std::int64_t key=1;key<=80;++key){index::RecordId found;const bool expected=key>30||key%2!=0;if(recovered.get_value(key,found)!=expected||(expected&&found!=value(key)))throw std::runtime_error("tree REDO lookup");}if(recovered.scan(1,80).size()!=65)throw std::runtime_error("tree REDO scan");}
void table_redo(){const auto db=path("ddb_redo_table.db"),wal=std::filesystem::path(db.string()+".wal");storage::PageManager pages(db);storage::LogManager log(wal);buffer::BufferPoolManager pool(pages,32,&log);const execution::Schema schema({{"payload",execution::ValueType::String}});const auto metadata=execution::TableHeap::create(pages,pool,schema);execution::TableHeap table(pages,pool,metadata,schema);concurrency::TransactionManager manager(&log);concurrency::LockManager locks;concurrency::TransactionCoordinator coordinator(locks,&log);concurrency::TransactionalTableHeap transactional(table,locks);auto transaction=manager.begin();std::vector<execution::RecordId> rows;for(int index=0;index<4;++index){auto row=transactional.insert(transaction,execution::Tuple{{std::string(2000,static_cast<char>('a'+index))}});if(!row)throw std::runtime_error("table insert");rows.push_back(*row);}if(!transactional.erase(transaction,rows[1]))throw std::runtime_error("table erase");coordinator.commit(transaction);const auto state=recovery::RecoveryAnalyzer::analyze(log);const auto before=wal_bytes(wal);pool.flush_all_pages();rewind_to_before_images(state,pool);pool.flush_all_pages();recovery::ReplayContext replay(pages,pool);if(!recovery::RedoEngine::run(state,replay).mutations_applied||wal_bytes(wal)!=before)throw std::runtime_error("table REDO replay");pool.flush_all_pages();execution::TableHeap recovered(pages,pool,metadata,schema);if(!recovered.validate_invariants()||recovered.scan().size()!=3)throw std::runtime_error("table REDO invariant");if(recovered.get(rows[1]).has_value()||!recovered.get(rows[0]).has_value()||!recovered.get(rows[2]).has_value()||!recovered.get(rows[3]).has_value())throw std::runtime_error("table REDO tuple state");}
}
int main(){try{bplus_redo();table_redo();}catch(const std::exception& error){std::cerr<<error.what()<<'\n';return 1;}std::cout<<"All structural REDO tests passed\n";}
