#include <filesystem>
#include <fstream>
#include <iostream>
#include <stdexcept>
#include <tuple>

#include "ddb/recovery/redo_engine.h"

namespace { using namespace ddb;
std::filesystem::path path(const char* name){auto file=std::filesystem::temp_directory_path()/name;std::error_code error;std::filesystem::remove(file,error);std::filesystem::remove(file.string()+".wal",error);return file;}
std::vector<char> bytes(const std::filesystem::path& file){std::ifstream input(file,std::ios::binary);return {std::istreambuf_iterator<char>(input),std::istreambuf_iterator<char>()};}
storage::PhysicalMutation mutation(storage::PageId page,unsigned char value,std::uint64_t sequence=0){std::vector<std::byte> after(storage::kPagePayloadSize,std::byte{value});return {page,storage::MutationKind::PayloadWrite,sequence,std::vector<std::byte>(storage::kPagePayloadSize),std::move(after)};}
recovery::RecoveryState state(storage::LogManager& log){return recovery::RecoveryAnalyzer::analyze(log);}

void committed_missing_and_idempotent(){const auto db=path("ddb_redo_missing.db"),wal=std::filesystem::path(db.string()+".wal");storage::LogManager log(wal);(void)log.append_begin(1);(void)log.append_page_allocate(1,storage::PageId(0));const auto lsn=log.append_physical_mutation(1,mutation(storage::PageId(0),7));(void)log.append_commit(1);log.flush();const auto before=bytes(wal);storage::PageManager pages(db);buffer::BufferPoolManager pool(pages,4,&log);auto analysis=state(log);recovery::ReplayContext replay(pages,pool);const auto first=recovery::RedoEngine::run(analysis,replay);if(first.pages_materialized!=1||first.mutations_applied!=1||!pages.is_page_allocated(storage::PageId(0)))throw std::runtime_error("missing-page redo");auto* page=pool.fetch_page(storage::PageId(0));if(!page||page->data()[0]!=std::byte{7}||page->lsn()!=lsn)throw std::runtime_error("redo payload or LSN");if(!pool.unpin_page(storage::PageId(0),false))throw std::runtime_error("unpin redo page");const auto second=recovery::RedoEngine::run(analysis,replay);if(second.mutations_applied||second.mutations_skipped_page_lsn!=1||bytes(wal)!=before)throw std::runtime_error("redo idempotence or WAL mutation");pool.flush_all_pages();if(!pool.validate_invariants())throw std::runtime_error("redo pool invariant");}
void existing_multi_page_and_selection(){const auto db=path("ddb_redo_existing.db"),wal=std::filesystem::path(db.string()+".wal");storage::LogManager log(wal);storage::PageManager pages(db);buffer::BufferPoolManager pool(pages,4,&log);const auto a=pages.allocate_page(),b=pages.allocate_page();(void)log.append_begin(2);const auto a1=log.append_physical_mutation(2,mutation(a,1));const auto b1=log.append_physical_mutation(2,mutation(b,2));const auto a2=log.append_physical_mutation(2,mutation(a,3,1));(void)log.append_commit(2);(void)log.append_begin(3);(void)log.append_page_allocate(3,storage::PageId(2));(void)log.append_physical_mutation(3,mutation(storage::PageId(2),9));(void)log.append_abort(3);(void)log.append_begin(4);(void)log.append_page_allocate(4,storage::PageId(3));(void)log.append_physical_mutation(4,mutation(storage::PageId(3),9));log.flush();recovery::ReplayContext replay(pages,pool);const auto metrics=recovery::RedoEngine::run(state(log),replay);if(metrics.mutations_applied!=3||pages.page_count()!=2)throw std::runtime_error("selection or multi-page redo");for(const auto [id,value,lsn]:std::vector<std::tuple<storage::PageId,std::byte,std::uint64_t>>{{a,std::byte{3},a2},{b,std::byte{2},b1}}){auto* page=pool.fetch_page(id);if(!page||page->data()[0]!=value||page->lsn()!=lsn)throw std::runtime_error("multi-page LSN");if(!pool.unpin_page(id,false))throw std::runtime_error("unpin multi-page");}(void)a1;auto* page=pool.fetch_page(a);page->data()[0]=std::byte{99};page->set_lsn(a2+10);if(!pool.unpin_page(a,true))throw std::runtime_error("unpin ahead page");if(recovery::RedoEngine::run(state(log),replay).mutations_applied!=0)throw std::runtime_error("ahead PageLSN was replayed");page=pool.fetch_page(a);if(page->data()[0]!=std::byte{99}||page->lsn()!=a2+10)throw std::runtime_error("ahead PageLSN regressed");if(!pool.unpin_page(a,false))throw std::runtime_error("unpin ahead check");}
}
int main(){try{committed_missing_and_idempotent();existing_multi_page_and_selection();}catch(const std::exception& error){std::cerr<<error.what()<<'\n';return 1;}std::cout<<"All REDO tests passed\n";}
