#include <cstring>
#include <filesystem>
#include <fstream>
#include <iostream>
#include <stdexcept>
#include "ddb/recovery/undo_engine.h"
namespace {using namespace ddb;
std::filesystem::path path(){auto p=std::filesystem::temp_directory_path()/"ddb_undo.db";std::error_code e;std::filesystem::remove(p,e);std::filesystem::remove(p.string()+".wal",e);return p;}
std::vector<char> raw(const std::filesystem::path&p){std::ifstream in(p,std::ios::binary);return {std::istreambuf_iterator<char>(in),{}};}
storage::PhysicalMutation mutation(storage::PageId p,unsigned char before,unsigned char after,std::uint64_t s){std::vector<std::byte>b(storage::kPagePayloadSize,std::byte{before}),a(storage::kPagePayloadSize,std::byte{after});return {p,storage::MutationKind::PayloadWrite,s,std::move(b),std::move(a)};}
void write(buffer::BufferPoolManager& pool,storage::PageId id,unsigned char value,std::uint64_t lsn){auto*p=pool.fetch_page(id);if(!p)throw std::runtime_error("pin");std::memset(p->data(),value,p->payload_size());p->set_lsn(lsn);if(!pool.unpin_page(id,true))throw std::runtime_error("unpin");}
}
int main(){try{const auto db=path();storage::PageManager pages(db);storage::LogManager log(db.string()+".wal");buffer::BufferPoolManager pool(pages,8,&log);const auto committed=pages.allocate_page(),same=pages.allocate_page(),other=pages.allocate_page(),allocated=pages.allocate_page();(void)log.append_begin(1);const auto committed_lsn=log.append_physical_mutation(1,mutation(committed,0,8,0));(void)log.append_commit(1);(void)log.append_begin(2);const auto first=log.append_physical_mutation(2,mutation(same,0,1,0));const auto second=log.append_physical_mutation(2,mutation(same,1,2,1));const auto third=log.append_physical_mutation(2,mutation(other,0,3,2));(void)log.append_page_allocate(2,allocated);(void)log.append_begin(3);const auto aborted=log.append_physical_mutation(3,mutation(other,3,4,0));(void)log.append_abort(3);log.flush();write(pool,committed,8,committed_lsn);write(pool,same,2,second);write(pool,other,4,aborted);const auto before=raw(log.path());const auto state=recovery::RecoveryAnalyzer::analyze(log);recovery::ReplayContext replay(pages,pool);const auto metrics=recovery::UndoEngine::run(state,replay);if(metrics.mutations_undone!=4||metrics.allocations_released!=1||pages.is_page_allocated(allocated)||raw(log.path())!=before)throw std::runtime_error("undo metrics/allocation/WAL");for(const auto[id,value,lsn]:std::vector<std::tuple<storage::PageId,std::byte,std::uint64_t>>{{committed,std::byte{8},committed_lsn},{same,std::byte{0},0},{other,std::byte{0},0}}){auto*p=pool.fetch_page(id);if(!p||p->data()[0]!=value||p->lsn()!=lsn)throw std::runtime_error("undo image or PageLSN");if(!pool.unpin_page(id,false))throw std::runtime_error("unpin verify");}const auto again=recovery::UndoEngine::run(state,replay);if(again.mutations_undone||raw(log.path())!=before||!pool.validate_invariants())throw std::runtime_error("repeated undo");try{(void)pool.fetch_page(allocated);throw std::runtime_error("uncommitted allocation fetchable");}catch(const storage::StorageError&){}(void)first;(void)third;std::cout<<"All UNDO tests passed\n";}catch(const std::exception&e){std::cerr<<e.what()<<'\n';return 1;}}
