#include "ddb/execution/table_heap.h"
#include "ddb/concurrency/transaction.h"
#include <cstring>
#include <stdexcept>
namespace ddb::execution { namespace {
constexpr std::size_t kHeader=24,kSlot=6; constexpr char kMetaMagic[]="DDBTH4"; constexpr char kDataMagic[]="DDBDP4";
void put16(std::byte*d,std::size_t p,std::uint16_t v){d[p]=std::byte(v&255);d[p+1]=std::byte(v>>8);} void put32(std::byte*d,std::size_t p,std::uint32_t v){for(int i=0;i<4;++i)d[p+i]=std::byte((v>>(i*8))&255);} void put64(std::byte*d,std::size_t p,std::uint64_t v){for(int i=0;i<8;++i)d[p+i]=std::byte((v>>(i*8))&255);}
std::uint16_t get16(const std::byte*d,std::size_t p){return std::to_integer<unsigned char>(d[p])|(std::uint16_t(std::to_integer<unsigned char>(d[p+1]))<<8);} std::uint32_t get32(const std::byte*d,std::size_t p){std::uint32_t v=0;for(int i=0;i<4;++i)v|=std::uint32_t(std::to_integer<unsigned char>(d[p+i]))<<(i*8);return v;} std::uint64_t get64(const std::byte*d,std::size_t p){std::uint64_t v=0;for(int i=0;i<8;++i)v|=std::uint64_t(std::to_integer<unsigned char>(d[p+i]))<<(i*8);return v;}
bool magic(const std::byte*d,const char*m){return std::memcmp(d,m,6)==0;} void release(ddb::buffer::BufferPoolManager& pool,ddb::storage::PageId id,bool dirty){if(!pool.unpin_page(id,dirty))throw std::runtime_error("buffer-pool unpin failed");} void data_init(ddb::storage::Page&p){p.clear();std::memcpy(p.data(),kDataMagic,6);put64(p.data(),8,ddb::storage::PageId::kInvalidValue);put16(p.data(),16,0);put16(p.data(),18,kHeader);put16(p.data(),20,ddb::storage::kPagePayloadSize);}
}
ddb::storage::PageId TableHeap::create(ddb::storage::PageManager& pm,ddb::buffer::BufferPoolManager& bp,const Schema& s,ddb::storage::MutationContext* mutations){if(s.columns().empty())throw std::invalid_argument("table schema must contain at least one column");auto id=pm.allocate_page();auto*p=bp.fetch_page(id);if(!p)throw std::runtime_error("cannot pin table metadata");if(mutations)mutations->watch(id);p->clear();std::memcpy(p->data(),kMetaMagic,6);put64(p->data(),8,ddb::storage::PageId::kInvalidValue);put64(p->data(),16,ddb::storage::PageId::kInvalidValue);if(mutations)mutations->finish(id,*p);release(bp,id,true);return id;}
ddb::storage::PageId TableHeap::create(ddb::concurrency::Transaction& transaction,ddb::storage::PageManager& pm,ddb::buffer::BufferPoolManager& bp,const Schema& s){if(s.columns().empty())throw std::invalid_argument("table schema must contain at least one column");auto id=transaction.allocate_page(pm);auto*p=bp.fetch_page(id);if(!p)throw std::runtime_error("cannot pin table metadata");auto& mutations=transaction.mutation_context(bp);mutations.watch(id);p->clear();std::memcpy(p->data(),kMetaMagic,6);put64(p->data(),8,ddb::storage::PageId::kInvalidValue);put64(p->data(),16,ddb::storage::PageId::kInvalidValue);mutations.finish(id,*p);release(bp,id,true);return id;}
TableHeap::TableHeap(ddb::storage::PageManager&pm,ddb::buffer::BufferPoolManager&bp,ddb::storage::PageId m,Schema s):pm_(pm),bp_(bp),meta_(m),schema_(std::move(s)){auto*p=bp_.fetch_page(m);if(!p||!magic(p->data(),kMetaMagic)){if(p)release(bp_,m,false);throw std::runtime_error("invalid table metadata page");}first_=ddb::storage::PageId(get64(p->data(),8));last_=ddb::storage::PageId(get64(p->data(),16));release(bp_,m,false);}
void TableHeap::write_metadata(){auto*p=bp_.fetch_page(meta_);if(!p)throw std::runtime_error("cannot pin table metadata");if(active_mutations_)active_mutations_->watch(meta_);put64(p->data(),8,first_.value());put64(p->data(),16,last_.value());if(active_mutations_)active_mutations_->finish(meta_,*p);release(bp_,meta_,true);}
std::vector<std::byte> TableHeap::serialize(const Tuple&t)const{if(!schema_.validates(t.values))throw std::invalid_argument("tuple does not match schema");std::vector<std::byte>b;for(const auto&v:t.values){if(const auto* integer=std::get_if<std::int64_t>(&v)){const auto n=b.size();b.resize(n+8);put64(b.data(),n,static_cast<std::uint64_t>(*integer));}else if(const auto* number=std::get_if<double>(&v)){const auto n=b.size();b.resize(n+8);std::memcpy(b.data()+n,number,sizeof(*number));}else if(const auto* boolean=std::get_if<bool>(&v)){b.push_back(*boolean?std::byte{1}:std::byte{0});}else {const auto& text=std::get<std::string>(v);const auto n=b.size();b.resize(n+4+text.size());put32(b.data(),n,static_cast<std::uint32_t>(text.size()));std::memcpy(b.data()+n+4,text.data(),text.size());}}return b;}
std::optional<Tuple> TableHeap::deserialize(const std::byte*d,std::size_t n)const{Tuple t;std::size_t p=0;for(const auto&c:schema_.columns()){if(c.type==ValueType::Int64){if(p+8>n)return{};t.values.emplace_back(static_cast<std::int64_t>(get64(d,p)));p+=8;}else if(c.type==ValueType::Double){if(p+8>n)return{};double x;std::memcpy(&x,d+p,8);t.values.emplace_back(x);p+=8;}else if(c.type==ValueType::Boolean){if(p+1>n)return{};t.values.emplace_back(std::to_integer<unsigned char>(d[p++])!=0);}else {if(p+4>n)return{};auto z=get32(d,p);p+=4;if(p+z>n)return{};t.values.emplace_back(std::string(reinterpret_cast<const char*>(d+p),z));p+=z;}}return p==n?std::optional<Tuple>(std::move(t)):std::nullopt;}
std::optional<RecordId> TableHeap::insert(const Tuple&t,ddb::storage::MutationContext* mutations){struct Scope{TableHeap& table;ddb::storage::MutationContext* mutations;ddb::concurrency::Transaction* transaction;~Scope(){table.active_mutations_=mutations;table.active_transaction_=transaction;}}scope{*this,active_mutations_,active_transaction_};active_mutations_=mutations;active_transaction_=nullptr;return insert_impl(t);}
std::optional<RecordId> TableHeap::insert(ddb::concurrency::Transaction& transaction,const Tuple&t){struct Scope{TableHeap& table;ddb::storage::MutationContext* mutations;ddb::concurrency::Transaction* transaction;~Scope(){table.active_mutations_=mutations;table.active_transaction_=transaction;}}scope{*this,active_mutations_,active_transaction_};active_transaction_=&transaction;active_mutations_=&transaction.mutation_context(bp_);return insert_impl(t);}
std::optional<RecordId> TableHeap::insert_impl(const Tuple&t){auto bytes=serialize(t);if(bytes.size()+kHeader+kSlot>ddb::storage::kPagePayloadSize)return{};ddb::storage::PageId id=last_;ddb::storage::Page*p=id.is_valid()?bp_.fetch_page(id):nullptr;if(!p||get16(p->data(),20)-get16(p->data(),18)<bytes.size()+kSlot){if(p)release(bp_,id,false);id=active_transaction_?active_transaction_->allocate_page(pm_):pm_.allocate_page();p=bp_.fetch_page(id);if(!p)throw std::runtime_error("cannot pin new data page");if(active_mutations_)active_mutations_->watch(id);data_init(*p);if(active_mutations_)active_mutations_->finish(id,*p);release(bp_,id,true);if(last_.is_valid()){auto*prev=bp_.fetch_page(last_);if(!prev)throw std::runtime_error("cannot pin previous data page");if(active_mutations_)active_mutations_->watch(last_);put64(prev->data(),8,id.value());if(active_mutations_)active_mutations_->finish(last_,*prev);release(bp_,last_,true);}else first_=id;last_=id;write_metadata();p=bp_.fetch_page(id);if(!p)throw std::runtime_error("cannot re-pin new data page");}if(active_mutations_)active_mutations_->watch(id);auto slots=get16(p->data(),16),start=get16(p->data(),18),end=get16(p->data(),20);end=static_cast<std::uint16_t>(end-bytes.size());std::memcpy(p->data()+end,bytes.data(),bytes.size());auto sp=kHeader+slots*kSlot;put16(p->data(),sp,end);put16(p->data(),sp+2,static_cast<std::uint16_t>(bytes.size()));put16(p->data(),sp+4,1);put16(p->data(),16,static_cast<std::uint16_t>(slots+1));put16(p->data(),18,static_cast<std::uint16_t>(start+kSlot));put16(p->data(),20,end);if(active_mutations_)active_mutations_->finish(id,*p);release(bp_,id,true);return RecordId{id,slots};}
std::optional<Tuple> TableHeap::get(RecordId r)const{if(!r.page_id.is_valid())return{};auto*p=bp_.fetch_page(r.page_id);if(!p)return{};if(!magic(p->data(),kDataMagic)||r.slot_id>=get16(p->data(),16)){release(bp_,r.page_id,false);return{};}auto sp=kHeader+r.slot_id*kSlot;auto offset=get16(p->data(),sp),len=get16(p->data(),sp+2);auto live=get16(p->data(),sp+4);if(!live||offset+len>ddb::storage::kPagePayloadSize){release(bp_,r.page_id,false);return{};}auto out=deserialize(p->data()+offset,len);release(bp_,r.page_id,false);return out;}
bool TableHeap::erase(RecordId r,ddb::storage::MutationContext* mutations){struct Scope{TableHeap& table;ddb::storage::MutationContext* mutations;ddb::concurrency::Transaction* transaction;~Scope(){table.active_mutations_=mutations;table.active_transaction_=transaction;}}scope{*this,active_mutations_,active_transaction_};active_mutations_=mutations;active_transaction_=nullptr;return erase_impl(r);}
bool TableHeap::erase(ddb::concurrency::Transaction& transaction,RecordId r){struct Scope{TableHeap& table;ddb::storage::MutationContext* mutations;ddb::concurrency::Transaction* transaction;~Scope(){table.active_mutations_=mutations;table.active_transaction_=transaction;}}scope{*this,active_mutations_,active_transaction_};active_transaction_=&transaction;active_mutations_=&transaction.mutation_context(bp_);return erase_impl(r);}
bool TableHeap::erase_impl(RecordId r){auto*p=bp_.fetch_page(r.page_id);if(!p||!magic(p->data(),kDataMagic)||r.slot_id>=get16(p->data(),16)){if(p)release(bp_,r.page_id,false);return false;}auto sp=kHeader+r.slot_id*kSlot;if(!get16(p->data(),sp+4)){release(bp_,r.page_id,false);return false;}if(active_mutations_)active_mutations_->watch(r.page_id);put16(p->data(),sp+4,0);if(active_mutations_)active_mutations_->finish(r.page_id,*p);release(bp_,r.page_id,true);return true;}
std::vector<std::pair<RecordId,Tuple>> TableHeap::scan()const{std::vector<std::pair<RecordId,Tuple>>out;for(auto id=first_;id.is_valid();){auto*p=bp_.fetch_page(id);if(!p)throw std::runtime_error("cannot pin data page");if(!magic(p->data(),kDataMagic)){release(bp_,id,false);throw std::runtime_error("invalid data page");}auto next=ddb::storage::PageId(get64(p->data(),8));auto slots=get16(p->data(),16);for(std::uint32_t i=0;i<slots;++i){auto sp=kHeader+i*kSlot;if(get16(p->data(),sp+4)){auto v=deserialize(p->data()+get16(p->data(),sp),get16(p->data(),sp+2));if(!v){release(bp_,id,false);throw std::runtime_error("corrupt tuple");}out.emplace_back(RecordId{id,i},std::move(*v));}}release(bp_,id,false);id=next;}return out;}
bool TableHeap::validate_invariants()const{try{for(auto id=first_;id.is_valid();){auto*p=bp_.fetch_page(id);if(!p||!magic(p->data(),kDataMagic)){if(p)release(bp_,id,false);return false;}auto slots=get16(p->data(),16),start=get16(p->data(),18),end=get16(p->data(),20);bool ok=start==kHeader+slots*kSlot&&end<=ddb::storage::kPagePayloadSize&&start<=end;for(std::uint32_t i=0;ok&&i<slots;++i){auto sp=kHeader+i*kSlot;auto o=get16(p->data(),sp),l=get16(p->data(),sp+2);ok=!get16(p->data(),sp+4)||(o>=end&&o+l<=ddb::storage::kPagePayloadSize&&deserialize(p->data()+o,l).has_value());}auto next=ddb::storage::PageId(get64(p->data(),8));release(bp_,id,false);if(!ok)return false;id=next;}return true;}catch(...){return false;}}
void TableHeap::flush(){bp_.flush_all_pages();}
}
